# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='names',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='names',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
